import { Question } from '@/types'

export const questions: Question[] = [
  {
    id: 'q1',
    domain: 'redFlag',
    text: 'Are you experiencing any of the following right now?',
    type: 'multi',
    options: [
      { label: 'Severe or throbbing tooth or jaw pain', value: 'pain', score: 0, redFlag: true },
      { label: 'Facial swelling or puffiness', value: 'swelling', score: 0, redFlag: true },
      { label: 'Fever alongside tooth or jaw pain', value: 'fever', score: 0, redFlag: true },
      { label: 'Uncontrolled bleeding in your mouth', value: 'bleeding', score: 0, redFlag: true },
      { label: 'A recent mouth or jaw injury', value: 'injury', score: 0, redFlag: true },
      { label: 'None of the above', value: 'none', score: 0 },
    ],
  },
  {
    id: 'q2',
    domain: 'caries',
    text: 'How often do you brush your teeth?',
    type: 'single',
    options: [
      { label: 'Twice a day or more', value: '2plus', score: 0 },
      { label: 'Once a day', value: '1', score: 1 },
      { label: 'A few times a week', value: 'few', score: 2 },
      { label: 'Rarely or never', value: 'rarely', score: 3 },
    ],
  },
  {
    id: 'q3',
    domain: 'caries',
    text: 'Do you use fluoride toothpaste?',
    type: 'single',
    options: [
      { label: 'Yes, always', value: 'yes', score: 0 },
      { label: 'Sometimes', value: 'sometimes', score: 1 },
      { label: 'No or not sure', value: 'no', score: 2 },
    ],
  },
  {
    id: 'q3a',
    domain: 'caries',
    text: 'How often do you clean between your teeth?',
    subtext: 'Floss, interdental brush, or water flosser all count.',
    type: 'single',
    options: [
      { label: 'Daily', value: 'daily', score: 0 },
      { label: 'A few times a week', value: 'few', score: 1 },
      { label: 'Rarely', value: 'rarely', score: 2 },
      { label: 'Never', value: 'never', score: 3 },
    ],
  },
  {
    id: 'q4',
    domain: 'caries',
    text: 'How often do you eat or drink something sugary?',
    subtext: 'Soda, juice, candy, sports drinks.',
    type: 'single',
    options: [
      { label: 'Rarely', value: 'rarely', score: 0 },
      { label: '1–2 times a day', value: '1to2', score: 1 },
      { label: '3–4 times a day', value: '3to4', score: 2 },
      { label: 'More than 4 times a day', value: '4plus', score: 3 },
    ],
  },
  {
    id: 'q5',
    domain: 'caries',
    text: 'How often do you drink acidic beverages?',
    subtext: 'Soda, energy drinks, citrus juice, vinegar drinks.',
    type: 'single',
    options: [
      { label: 'Rarely', value: 'rarely', score: 0 },
      { label: 'Once a day', value: '1', score: 1 },
      { label: 'Multiple times a day', value: 'multi', score: 2 },
    ],
  },
  {
    id: 'q6',
    domain: 'perio',
    text: 'Do your gums bleed when you brush or floss?',
    type: 'single',
    options: [
      { label: 'Never', value: 'never', score: 0 },
      { label: 'Occasionally', value: 'occasionally', score: 1 },
      { label: 'Often or always', value: 'often', score: 2 },
    ],
  },
  {
    id: 'q7',
    domain: 'perio',
    text: 'Have you noticed any of these?',
    type: 'multi',
    options: [
      { label: 'Gums pulling away from your teeth', value: 'receding', score: 2 },
      { label: 'Loose or shifting teeth', value: 'loose', score: 2 },
      { label: 'Persistent bad breath despite brushing', value: 'breath', score: 1 },
      { label: 'Visible hole, broken tooth, or broken filling', value: 'cavity', score: 2 },
      { label: 'None of the above', value: 'none', score: 0 },
    ],
  },
  {
    id: 'q8',
    domain: 'perio',
    text: 'Do you smoke or use any tobacco products?',
    type: 'single',
    options: [
      { label: 'No', value: 'no', score: 0 },
      { label: 'I quit', value: 'quit', score: 1 },
      { label: 'Yes, occasionally', value: 'occasional', score: 2 },
      { label: 'Yes, regularly', value: 'regular', score: 3 },
    ],
  },
  {
    id: 'q9',
    domain: 'access',
    text: 'When did you last visit a dentist?',
    type: 'single',
    options: [
      { label: 'Within the last 6 months', value: '6mo', score: 0 },
      { label: '6–12 months ago', value: '12mo', score: 1 },
      { label: '1–2 years ago', value: '2yr', score: 2 },
      { label: 'More than 2 years ago', value: '2plus', score: 3 },
      { label: 'Never', value: 'never', score: 4 },
    ],
  },
  {
    id: 'q10',
    domain: 'access',
    text: 'Has anything made it difficult to see a dentist?',
    type: 'multi',
    options: [
      { label: 'Cost or insurance', value: 'cost', score: 1 },
      { label: 'Anxiety or fear', value: 'anxiety', score: 1 },
      { label: 'Access or transportation', value: 'transport', score: 1 },
      { label: 'Nothing specific', value: 'none', score: 0 },
      { label: 'I see a dentist regularly', value: 'regular', score: 0 },
    ],
  },
  {
    id: 'q11',
    domain: 'context',
    text: 'What is your age group?',
    type: 'single',
    options: [
      { label: 'Under 18', value: 'under18', score: 0 },
      { label: '18–39', value: '18to39', score: 0 },
      { label: '40–64', value: '40to64', score: 0 },
      { label: '65 or older', value: '65plus', score: 1 },
    ],
  },
  {
    id: 'q12',
    domain: 'context',
    text: 'Do any of these apply to you?',
    type: 'multi',
    options: [
      { label: 'Currently pregnant', value: 'pregnant', score: 1 },
      { label: 'I have diabetes', value: 'diabetes', score: 1 },
      { label: 'Immune system condition', value: 'immune', score: 1 },
      { label: 'I take medications that cause dry mouth', value: 'drymouth', score: 1 },
      { label: 'None of the above', value: 'none', score: 0 },
    ],
  },
]
